version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - /home/mlluiz/Dev/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    restart: always